namespace Gcds.Blazor.Components;

public static class GcdsComponentCatalog
{
    public static IReadOnlyDictionary<string, Type> Components { get; } = new Dictionary<string, Type>
    {
        ["gcds-alert"] = typeof(GcdsAlert),
        ["gcds-breadcrumbs"] = typeof(GcdsBreadcrumbs),
        ["gcds-breadcrumbs-item"] = typeof(GcdsBreadcrumbsItem),
        ["gcds-button"] = typeof(GcdsButton),
        ["gcds-card"] = typeof(GcdsCard),
        ["gcds-checkboxes"] = typeof(GcdsCheckboxes),
        ["gcds-container"] = typeof(GcdsContainer),
        ["gcds-date-input"] = typeof(GcdsDateInput),
        ["gcds-date-modified"] = typeof(GcdsDateModified),
        ["gcds-details"] = typeof(GcdsDetails),
        ["gcds-error-message"] = typeof(GcdsErrorMessage),
        ["gcds-error-summary"] = typeof(GcdsErrorSummary),
        ["gcds-fieldset"] = typeof(GcdsFieldset),
        ["gcds-file-uploader"] = typeof(GcdsFileUploader),
        ["gcds-footer"] = typeof(GcdsFooter),
        ["gcds-grid"] = typeof(GcdsGrid),
        ["gcds-grid-col"] = typeof(GcdsGridCol),
        ["gcds-header"] = typeof(GcdsHeader),
        ["gcds-heading"] = typeof(GcdsHeading),
        ["gcds-hint"] = typeof(GcdsHint),
        ["gcds-icon"] = typeof(GcdsIcon),
        ["gcds-input"] = typeof(GcdsInput),
        ["gcds-label"] = typeof(GcdsLabel),
        ["gcds-lang-toggle"] = typeof(GcdsLangToggle),
        ["gcds-link"] = typeof(GcdsLink),
        ["gcds-nav-group"] = typeof(GcdsNavGroup),
        ["gcds-nav-link"] = typeof(GcdsNavLink),
        ["gcds-notice"] = typeof(GcdsNotice),
        ["gcds-pagination"] = typeof(GcdsPagination),
        ["gcds-radios"] = typeof(GcdsRadios),
        ["gcds-search"] = typeof(GcdsSearch),
        ["gcds-select"] = typeof(GcdsSelect),
        ["gcds-side-nav"] = typeof(GcdsSideNav),
        ["gcds-signature"] = typeof(GcdsSignature),
        ["gcds-sr-only"] = typeof(GcdsSrOnly),
        ["gcds-stepper"] = typeof(GcdsStepper),
        ["gcds-table"] = typeof(GcdsTable),
        ["gcds-text"] = typeof(GcdsText),
        ["gcds-textarea"] = typeof(GcdsTextarea),
        ["gcds-top-nav"] = typeof(GcdsTopNav),
        ["gcds-topic-menu"] = typeof(GcdsTopicMenu),
    };
}
